project:
  type: book

book:
  title: "Risk Management and Financial Institutions"
  author: "Tomáš Plíhal"
  date: "2023-09-18"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  sidebar:
    logo: logo.png
  chapters:
    - index.qmd
    - week_01.qmd
    - week_02.qmd
    - week_03.qmd
    - week_04.qmd
    - week_05.qmd
    - week_06.qmd
    - week_07.qmd
    - week_08.qmd
    - week_09.qmd
    - week_10.qmd
    - week_11.qmd
    - week_12.qmd
    - week_13.qmd

format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt



