<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Credit Risk – Risk Management and Financial Institutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./week_10.html" rel="next">
<link href="./week_08.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./week_09.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Credit Risk</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Risk Management and Financial Institutions</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Risk-Management-and-Financial-Institutions.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Risk-Management-and-Financial-Institutions.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Risk Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Revision of the Basic Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Forwards and Futures Strategies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Options Strategies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Volatility, Correlations, and Copulas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Market Risk I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reading Week</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Market Risk II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_09.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Credit Risk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Operational Risk, Liquidity Risk, and Model Risk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Climate Risk and Enterprise Risk Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regulation, Economic Capital, and RAROC</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Financial Innovation and Risk Management Mistakes</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#estimating-default-probabilities" id="toc-estimating-default-probabilities" class="nav-link active" data-scroll-target="#estimating-default-probabilities"><span class="header-section-number">9.1</span> Estimating Default Probabilities</a></li>
  <li><a href="#xvas" id="toc-xvas" class="nav-link" data-scroll-target="#xvas"><span class="header-section-number">9.2</span> xVAs</a></li>
  <li><a href="#credit-value-at-risk-credit-var" id="toc-credit-value-at-risk-credit-var" class="nav-link" data-scroll-target="#credit-value-at-risk-credit-var"><span class="header-section-number">9.3</span> Credit Value at Risk (Credit VaR)</a></li>
  <li><a href="#practice-questions-and-problems" id="toc-practice-questions-and-problems" class="nav-link" data-scroll-target="#practice-questions-and-problems"><span class="header-section-number">9.4</span> Practice Questions and Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Credit Risk</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>References:</strong></p>
<ul>
<li>Hull, J. C. 2023. Risk Management and Financial Institutions. Wiley Finance.
<ul>
<li>Chapter 17 - Estimating Default Probabilities</li>
<li>Chapter 18 - xVAs</li>
<li>Chapter 19 - Credit Value at Risk</li>
</ul></li>
</ul>
<p><strong>Learning outcomes:</strong></p>
<ul>
<li>Understand default probabilities, recovery rates, and their importance in risk management.<br>
</li>
<li>Explore credit ratings, CDS markets, and credit spreads for estimating defaults.<br>
</li>
<li>Distinguish between real-world and risk-neutral probabilities and methods to infer them.</li>
<li>Understand Credit Value Adjustment (CVA), Debit Value Adjustment (DVA), and their implications.<br>
</li>
<li>Learn the risks and complexities in CVA, including wrong-way and right-way risk.<br>
</li>
<li>Explore Credit Value at Risk (VaR) and methods to calculate VaR or Expected Shortfall.</li>
</ul>
<section id="estimating-default-probabilities" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="estimating-default-probabilities"><span class="header-section-number">9.1</span> Estimating Default Probabilities</h2>
<section id="credit-ratings" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="credit-ratings"><span class="header-section-number">9.1.1</span> Credit Ratings</h3>
<section id="credit-rating-agencies-e.g.-moodys-sp-fitch" class="level4">
<h4 class="anchored" data-anchor-id="credit-rating-agencies-e.g.-moodys-sp-fitch">Credit Rating Agencies (e.g., Moody’s, S&amp;P, Fitch)</h4>
<p>Credit rating agencies assign ratings to corporate bonds, providing an assessment of the issuer’s creditworthiness. These ratings are typically stable and change infrequently, as agencies aim to avoid frequent reversals. They often use a “through-the-cycle” approach, focusing on long-term credit stability and disregarding short-term economic fluctuations.</p>
</section>
<section id="market-based-providers-e.g.-moodys-kmv-kamakura" class="level4">
<h4 class="anchored" data-anchor-id="market-based-providers-e.g.-moodys-kmv-kamakura">Market-Based Providers (e.g., Moody’s KMV, Kamakura)</h4>
<p>Unlike traditional rating agencies, these companies estimate default probabilities using market data, such as equity prices and other financial variables. Their models are more dynamic and responsive to real-time market changes, prioritizing timely insights over stability.</p>
</section>
<section id="internal-credit-ratings-in-banks" class="level4">
<h4 class="anchored" data-anchor-id="internal-credit-ratings-in-banks">Internal Credit Ratings in Banks</h4>
<p>Banks use internal credit rating systems to evaluate the credit risk of small and medium-sized enterprises (SMEs) that lack publicly traded debt. These ratings incorporate financial ratios, such as:</p>
<ul>
<li><strong>Profitability ratios:</strong> e.g., Return on Assets (ROA).<br>
</li>
<li><strong>Leverage ratios:</strong> e.g., Debt-to-Equity Ratio.</li>
</ul>
<p>Additionally, banks analyze projected cash flow statements to assess a firm’s ability to meet its debt obligations.</p>
</section>
<section id="altmans-z-score" class="level4">
<h4 class="anchored" data-anchor-id="altmans-z-score">Altman’s Z-Score</h4>
<p>The Z-Score is a statistical model developed to predict corporate default risk using a combination of accounting ratios. The formula is:</p>
<p><span class="math display">\[
Z = 1.2 X_1 + 1.4 X_2 + 3.3 X_3 + 0.6 X_4 + 0.999 X_5
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(X_1\)</span>: Working capital / Total assets<br>
</li>
<li><span class="math inline">\(X_2\)</span>: Retained earnings / Total assets<br>
</li>
<li><span class="math inline">\(X_3\)</span>: Earnings before interest and taxes (EBIT) / Total assets<br>
</li>
<li><span class="math inline">\(X_4\)</span>: Market value of equity / Book value of total liabilities<br>
</li>
<li><span class="math inline">\(X_5\)</span>: Sales / Total assets</li>
</ul>
<p><strong>Interpretation of Z-Scores:</strong></p>
<ul>
<li><span class="math inline">\(Z &gt; 3.0\)</span>: Low probability of default.<br>
</li>
<li><span class="math inline">\(2.7 &lt; Z &lt; 3.0\)</span>: Company is on alert.<br>
</li>
<li><span class="math inline">\(1.8 &lt; Z &lt; 2.7\)</span>: Moderate risk of default.<br>
</li>
<li><span class="math inline">\(Z &lt; 1.8\)</span>: High likelihood of financial distress.</li>
</ul>
<p>This framework is widely used for early warning signals and credit risk assessment in non-financial firms.</p>
</section>
</section>
<section id="historical-default-probabilities" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="historical-default-probabilities"><span class="header-section-number">9.1.2</span> Historical Default Probabilities</h3>
<p>Credit rating agencies compile historical data to track default experiences over time, segmented by credit ratings. This information provides valuable insights into the likelihood of default for bonds of varying creditworthiness.</p>
<p><strong>Table of Cumulative Default Probabilities (1981–2020):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Time (years)</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">10</th>
<th style="text-align: center;">15</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AAA</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">0.34</td>
<td style="text-align: center;">0.51</td>
<td style="text-align: center;">0.70</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: center;">AA</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">0.70</td>
<td style="text-align: center;">0.99</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.46</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">1.20</td>
<td style="text-align: center;">1.84</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">1.14</td>
<td style="text-align: center;">1.54</td>
<td style="text-align: center;">2.27</td>
<td style="text-align: center;">3.24</td>
<td style="text-align: center;">4.54</td>
</tr>
<tr class="odd">
<td style="text-align: center;">BB</td>
<td style="text-align: center;">0.63</td>
<td style="text-align: center;">1.93</td>
<td style="text-align: center;">3.46</td>
<td style="text-align: center;">4.99</td>
<td style="text-align: center;">6.43</td>
<td style="text-align: center;">8.89</td>
<td style="text-align: center;">11.64</td>
<td style="text-align: center;">14.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">3.34</td>
<td style="text-align: center;">7.80</td>
<td style="text-align: center;">11.75</td>
<td style="text-align: center;">14.89</td>
<td style="text-align: center;">17.35</td>
<td style="text-align: center;">20.99</td>
<td style="text-align: center;">24.62</td>
<td style="text-align: center;">28.24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CCC/C</td>
<td style="text-align: center;">28.30</td>
<td style="text-align: center;">38.33</td>
<td style="text-align: center;">43.42</td>
<td style="text-align: center;">46.36</td>
<td style="text-align: center;">48.58</td>
<td style="text-align: center;">50.75</td>
<td style="text-align: center;">52.76</td>
<td style="text-align: center;">54.76</td>
</tr>
</tbody>
</table>
<ul>
<li>For investment-grade bonds (BBB and above), the probability of default typically increases over time.</li>
<li>For lower-rated bonds, default probabilities may decrease as weaker issuers default early, leaving more resilient entities in the sample.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Default Probabilities for BBB Bonds:</p>
<ul>
<li>A bond initially rated BBB has a 0.16% chance of defaulting in the first year, 0.43% in the second year, etc.</li>
<li><strong>Yearly Probability Calculation</strong>: The probability of defaulting in a specific year can be calculated by subtraction. E.g., for the second year, <span class="math inline">\(0.43\% - 0.16\% = 0.27\%\)</span>.</li>
</ul>
</div>
</div>
<section id="unconditional-default-probability" class="level4">
<h4 class="anchored" data-anchor-id="unconditional-default-probability">Unconditional Default Probability</h4>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Unconditional Default Probabilities:</strong> Reflect the likelihood of default during a specific year as measured from the start of the observation period.</p>
</div>
</div>
<p>The unconditional default probability is the increase in cumulative probability during a specific year.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unconditional probability of default for CCC/C bonds during third year: <span class="math display">\[
43.42\% - 38.33\% = 5.09\%.
\]</span></p>
</div>
</div>
</section>
<section id="conditional-default-probability" class="level4">
<h4 class="anchored" data-anchor-id="conditional-default-probability">Conditional Default Probability</h4>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conditional Default Probabilities:</strong> Indicate the probability of default in a given year, assuming no prior default.</p>
</div>
</div>
<p>The conditional probability adjusts for survival until a specific time, offering more context for ongoing risk management.</p>
<p><strong>Steps to Calculate:</strong></p>
<ol type="1">
<li>Calculate the probability of surviving until the end of the previous year.<br>
</li>
<li>Divide the yearly default probability by the survival probability.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Conditional probability of default for CCC/C bonds during third year: <span class="math display">\[
100\% - 38.33\% = 61.67\%
\]</span> <span class="math display">\[
\frac{5.09\%}{61.67\%} = 8.25\%.
\]</span></p>
</div>
</div>
</section>
<section id="applications" class="level4">
<h4 class="anchored" data-anchor-id="applications">Applications</h4>
<ul>
<li><strong>Unconditional Probabilities:</strong> Useful for static, long-term risk assessments.</li>
<li><strong>Conditional Probabilities:</strong> Crucial for dynamic risk management as they reflect updated information and ongoing contexts.</li>
</ul>
<p>By analyzing these probabilities, financial practitioners can better understand and manage the risk profiles of bonds, making informed investment and credit decisions.</p>
</section>
<section id="hazard-rates" class="level4">
<h4 class="anchored" data-anchor-id="hazard-rates">Hazard Rates</h4>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>hazard rate</strong> (<span class="math inline">\(\lambda(t)\)</span>) represents the intensity of default over a short time period, conditional on the entity’s survival until that time. It bridges the concepts of conditional and unconditional probabilities, offering a dynamic measure of default risk.</p>
</div>
</div>
<ul>
<li>The hazard rate measures the likelihood of default in a short time interval, given no prior default.</li>
<li>It incorporates survival probabilities to provide a nuanced understanding of credit risk over time.</li>
<li><span class="math inline">\(V(t)\)</span> is the cumulative probability of the company surviving to time <span class="math inline">\(t\)</span>.</li>
</ul>
<p><strong>Conditional Probability of Default:</strong><br>
<span class="math display">\[
\frac{V(t) - V(t + \Delta t)}{V(t)} = \lambda(t) \Delta t
\]</span> <strong>Cumulative Survival Probability:</strong><br>
<span class="math display">\[
V(t) = e^{-\int_{0}^{t} \lambda(\tau)d\tau}
\]</span> <strong>Cumulative Default Probability:</strong><br>
<span class="math display">\[
Q(t) = 1 - e^{-\int_{0}^{t} \lambda(\tau)d\tau} = 1 - e^{-\lambda(t) t}
\]</span></p>
</section>
<section id="example-calculations-with-hazard-rates" class="level4">
<h4 class="anchored" data-anchor-id="example-calculations-with-hazard-rates">Example Calculations with Hazard Rates</h4>
<p>Assume a constant hazard rate of <span class="math inline">\(1.5\%\)</span> per year. The default probabilities for each year are computed as follows:</p>
<p><span class="math display">\[
Q(1) = 1 - e^{-0.015 \times 1} = 0.0149
\]</span> <span class="math display">\[
Q(2) = 1 - e^{-0.015 \times 2} = 0.0296
\]</span> <span class="math display">\[
Q(3) = 1 - e^{-0.015 \times 3} = 0.0440
\]</span> <span class="math display">\[
Q(4) = 1 - e^{-0.015 \times 4} = 0.0582
\]</span> <span class="math display">\[
Q(5) = 1 - e^{-0.015 \times 5} = 0.0723
\]</span></p>
<ul>
<li><p><strong>Unconditional Default Probability:</strong> The probability of default in the 4th year is the difference between cumulative probabilities of the 4th and 3rd years:<br>
<span class="math display">\[
Q(4) - Q(3) = 0.0582 - 0.0440 = 0.0142
\]</span></p></li>
<li><p><strong>Conditional Default Probability:</strong> The probability of default in the 4th year, assuming survival until the end of the 3rd year:<br>
<span class="math display">\[
\frac{0.0142}{1 - Q(3)} = \frac{0.0142}{1 - 0.0440} = 0.0149
\]</span></p></li>
<li><p>Hazard rates are essential for modeling time-dependent default risk in credit risk management.</p></li>
<li><p>They provide a more granular and dynamic perspective compared to static probabilities, aiding in real-time risk assessments and pricing of credit derivatives.</p></li>
</ul>
</section>
</section>
<section id="recovery-rates" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="recovery-rates"><span class="header-section-number">9.1.3</span> Recovery Rates</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>recovery rate</strong> of a bond is the percentage of the principal amount recovered after default, typically based on the bond’s trading price about one month post-default. This metric provides critical insights into creditor losses and varies based on the bond’s seniority and prevailing economic conditions.</p>
</div>
</div>
<ul>
<li>The recovery rate represents the value creditors reclaim through partial payments or asset liquidation.<br>
</li>
<li>Recovery rates differ significantly based on bond category:
<ul>
<li><strong>First Lien Bonds:</strong> 54.6% recovery.<br>
</li>
<li><strong>Junior Subordinated Bonds:</strong> 22.3% recovery.<br>
</li>
</ul></li>
<li>Recovery rates are inversely related to default rates:
<ul>
<li><strong>Good economic conditions:</strong> Higher recovery rates.<br>
</li>
<li><strong>Poor economic conditions:</strong> Lower recovery rates.<br>
</li>
</ul></li>
<li>In challenging economic periods, the combination of high default rates and low recovery rates exacerbates creditor losses.</li>
<li>Understanding recovery rate trends is crucial for credit risk assessment, pricing of distressed debt, and strategic risk management.</li>
</ul>
</section>
<section id="credit-default-swaps-cds" class="level3" data-number="9.1.4">
<h3 data-number="9.1.4" class="anchored" data-anchor-id="credit-default-swaps-cds"><span class="header-section-number">9.1.4</span> Credit Default Swaps (CDS)</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A Credit Default Swap (CDS) is a financial contract that acts as a form of insurance against the risk of credit default.</p>
</div>
</div>
<ul>
<li>It involves two parties: the protection buyer, who pays periodic premiums (typically quarterly), and the protection seller, who compensates the buyer if a specified credit event, such as a default, occurs.</li>
<li>CDS contracts can be linked to corporate bonds, government bonds, or other credit instruments, providing the buyer with protection against the risk of the issuer defaulting on the underlying instrument.</li>
</ul>
<p>The pricing of a CDS is determined by several factors, including the creditworthiness of the reference entity, current market conditions, and the maturity of the swap. CDS contracts play a crucial role in price discovery for credit risk and significantly influence overall market liquidity and stability.</p>
<section id="cds-spread" class="level4">
<h4 class="anchored" data-anchor-id="cds-spread">CDS Spread</h4>
<ul>
<li>The <strong>CDS spread</strong> is the annual premium, usually expressed in basis points (bps), that the protection buyer pays to the protection seller over the duration of the contract.</li>
<li>The spread is calculated as a percentage of the notional amount of the underlying credit instrument.</li>
<li>A wider CDS spread typically indicates a higher perceived risk of default for the underlying entity, whereas a narrower spread suggests lower perceived risk.</li>
</ul>
<p>For example, if the CDS spread for a particular corporate bond is 200 bps, the buyer pays the seller 2% of the notional amount annually for the protection. The CDS spread serves as a valuable indicator of credit risk and market sentiment concerning the referenced entity.</p>
</section>
<section id="credit-indices" class="level4">
<h4 class="anchored" data-anchor-id="credit-indices">Credit Indices</h4>
<ul>
<li><strong>Credit indices</strong> are benchmarks that track the performance of a basket of credit instruments, such as bonds or credit default swaps.</li>
<li>These indices often include a diversified portfolio of credit instruments representing various sectors, credit ratings, or geographic regions.</li>
<li>Credit indices are used to gauge overall market health, providing insights into credit risk, liquidity, and investor sentiment.</li>
</ul>
<p>Popular credit indices include the <strong>Markit iTraxx</strong> in Europe and the <strong>CDX</strong> in North America, which track CDS spreads across different categories of issuers. These indices enhance liquidity in the credit market by creating standardized products that can be traded more easily.</p>
</section>
</section>
<section id="credit-spreads" class="level3" data-number="9.1.5">
<h3 data-number="9.1.5" class="anchored" data-anchor-id="credit-spreads"><span class="header-section-number">9.1.5</span> Credit Spreads</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>credit spread</strong> is the additional rate of interest per annum that investors require for bearing a particular credit risk.</p>
</div>
</div>
<ul>
<li>Credit spreads can be measured using <strong>CDS spreads</strong> or <strong>bond yield spreads</strong> (calculated as the difference between a bond’s yield and the yield on a risk-free bond).</li>
<li>A CDS can effectively hedge a corporate bond, essentially converting it into a risk-free bond.</li>
<li>The <strong>N-year CDS spread</strong> should approximate the yield difference between an N-year corporate bond and an N-year risk-free bond. However, liquidity constraints can limit the effectiveness of arbitrage opportunities between CDS and bonds.</li>
<li>CDS contracts provide a direct estimate of the credit spread, while <strong>risk-free rates</strong> are generally derived from Treasury bonds.</li>
<li>Notably, implied risk-free rates are often found to be higher than Treasury rates.</li>
<li><strong>Asset swaps</strong> also provide direct estimates of excess bond yields over a floating reference rate.</li>
</ul>
<section id="cdsbond-basis" class="level4">
<h4 class="anchored" data-anchor-id="cdsbond-basis">CDS–Bond Basis</h4>
<p>The <strong>CDS–Bond Basis</strong> is the difference between the CDS spread and the bond yield spread:</p>
<p><span class="math display">\[
\text{CDS-Bond Basis} = \text{CDS Spread} - \text{Bond Yield Spread}
\]</span></p>
<p>Various factors, such as counterparty default risk and bond price fluctuations, can cause the CDS–Bond Basis to deviate from zero. Historically, the CDS–Bond Basis was positive before the 2007 financial crisis, but it has since tended to be small and negative.</p>
</section>
</section>
<section id="estimating-default-probabilities-from-credit-spreads" class="level3" data-number="9.1.6">
<h3 data-number="9.1.6" class="anchored" data-anchor-id="estimating-default-probabilities-from-credit-spreads"><span class="header-section-number">9.1.6</span> Estimating Default Probabilities from Credit Spreads</h3>
<p>Estimating default probabilities from credit spreads involves using market indicators such as CDS spreads, bond yield spreads, or asset swap spreads to infer the likelihood of default.</p>
<section id="approximate-calculation" class="level4">
<h4 class="anchored" data-anchor-id="approximate-calculation">Approximate Calculation</h4>
<p>This method provides a straightforward way to estimate average default probabilities when the bond price is near par value.</p>
<p><strong>Scenario</strong>: Suppose a 5-year credit spread is 240 basis points (or 2.4%), and the recovery rate is 40%.</p>
<p><strong>Formula</strong>: The average hazard rate (<span class="math inline">\(\overline{\lambda}\)</span>) over the time horizon <span class="math inline">\(T\)</span> is given by: <span class="math display">\[
\overline{\lambda} = \frac{s(T)}{1 - R}
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(s(T)\)</span>: Credit spread for maturity <span class="math inline">\(T\)</span>,</li>
<li><span class="math inline">\(R\)</span>: Recovery rate,</li>
<li><span class="math inline">\(\overline{\lambda}\)</span>: Average hazard rate.</li>
</ul>
<p>Using the given parameters: <span class="math display">\[
\overline{\lambda} = \frac{0.024}{1 - 0.4} = 4\%
\]</span></p>
<p>This method is effective for credit default swaps (CDS), bond yield spreads, and asset swap spreads. It assumes that the bond price is close to its par value.</p>
<!-- #### A More Exact Calculation

A more precise method is necessary when bond prices deviate significantly from par
value. This approach incorporates additional variables, such as the bond price, coupon
rate, and yield, to estimate default probabilities more accurately.

**General Process**:

1. Compare the price of the corporate bond to a similar risk-free bond.
2. Estimate the expected loss from default over the bond's life.
3. Equate the expected default loss to the present value of future default losses.
4. Solve for the default probability ($Q$) that satisfies the relationship.

- Provides higher accuracy than the approximate method.
- Adjusts for complex market conditions, such as variations in bond prices and yields.

This approach is particularly useful in volatile markets where bond prices may reflect
more nuanced credit risk factors. -->
</section>
</section>
<section id="comparison-of-default-probability-estimates" class="level3" data-number="9.1.7">
<h3 data-number="9.1.7" class="anchored" data-anchor-id="comparison-of-default-probability-estimates"><span class="header-section-number">9.1.7</span> Comparison of Default Probability Estimates</h3>
<p>When estimating default probabilities, it is essential to distinguish between probabilities derived from historical data (real-world) and those inferred from credit spreads (risk-neutral).</p>
<ul>
<li><strong>Real-World Probabilities</strong>: Derived from historical default rates, representing actual default frequencies observed in the past.</li>
<li><strong>Risk-Neutral Probabilities</strong>: Derived from credit spreads and market prices, reflecting the probability of default adjusted for investor risk preferences and market expectations.</li>
</ul>
<p>Hazard rates estimated from credit spreads are generally <strong>higher</strong> than those derived from historical data. This disparity grows more pronounced as credit quality declines, and several factors contribute to these differences:</p>
<ol type="1">
<li><strong>Illiquidity of Corporate Bonds</strong>: Corporate bonds often trade in less liquid markets, leading to higher spreads.</li>
<li><strong>Systematic Risk</strong>: Defaults are often correlated, increasing perceived risk in credit spreads.</li>
<li><strong>Non-Systematic Risk</strong>: Corporate bonds carry firm-specific risks that are harder to diversify compared to equity portfolios.</li>
</ol>
<ul>
<li>Use <strong>risk-neutral default probabilities</strong> for:
<ul>
<li>Valuing credit derivatives: Required for pricing instruments like CDS or CDOs.</li>
<li>Estimating the impact of default risk: Particularly when using market-consistent measures.</li>
</ul></li>
<li>Use <strong>real-world default probabilities</strong> for:
<ul>
<li>Scenario analyses: Assessing potential future losses under various economic conditions.</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>The Merton (1974) model provides a theoretical foundation for calculating default probabilities. It treats a company’s equity as a <strong>call option</strong> on its assets, with the strike price equivalent to the debt repayment amount. This approach links default risk to asset value volatility, offering a structural method for default probability estimation.</p>
</blockquote>
</section>
</section>
<section id="xvas" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="xvas"><span class="header-section-number">9.2</span> xVAs</h2>
<p>Over-the-counter (OTC) derivatives are cleared through either <strong>Central Clearing Parties (CCPs)</strong> or bilateral agreements. Regulatory frameworks now require most standardized derivatives to be cleared via CCPs, significantly reducing credit risk. However, bilaterally cleared transactions necessitate additional collateral to manage credit risk. Despite these safeguards, certain OTC transactions, such as those with non-financial end-users, remain outside the scope of these regulations.</p>
<p>Assessing credit risk in derivatives is more complex than in traditional loans due to the uncertainty of future exposure and the potentially unlimited loss. To manage this complexity, various adjustments, collectively known as <strong>xVAs</strong>, are used. These include:</p>
<ul>
<li><strong>Credit Value Adjustment (CVA)</strong>: Quantifies the counterparty credit risk.<br>
</li>
<li><strong>Debit Value Adjustment (DVA)</strong>: Reflects the counterparty’s perspective of the dealer’s credit risk.<br>
</li>
<li><strong>Funding Value Adjustment (FVA)</strong>, <strong>Margin Value Adjustment (MVA)</strong>, and <strong>Capital Value Adjustment (KVA)</strong>: Capture other costs and risks in derivative transactions.</li>
</ul>
<p>This discussion focuses on <strong>CVA</strong>, the primary metric for quantifying a dealer’s credit risk in bilaterally cleared transactions.</p>
<section id="credit-exposure-on-derivatives" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="credit-exposure-on-derivatives"><span class="header-section-number">9.2.1</span> Credit Exposure on Derivatives</h3>
<p>Credit exposure in derivatives arises from market value fluctuations, unlike loans with fixed exposures. Future exposure is uncertain, and losses can theoretically be unlimited. Consider a single bilaterally cleared transaction with no collateral posted:</p>
<ol type="1">
<li><strong>Liability for the dealer (e.g., short option)</strong>: The dealer has no credit exposure.</li>
<li><strong>Asset for the dealer (e.g., long option)</strong>: The dealer bears the credit exposure.<br>
</li>
<li><strong>Variable exposure (e.g., forward or swap)</strong>: Exposure fluctuates over time, depending on market conditions.</li>
</ol>
<p>For multiple transactions between a dealer and a counterparty, exposures are often <strong>netted</strong>. The dealer’s net exposure is given by:<br>
<span class="math display">\[
\text{max}(V, 0)
\]</span> where <span class="math inline">\(V\)</span> represents the net market value of all transactions. The dealer must consider both current and potential future exposure when assessing credit risk.</p>
</section>
<section id="credit-value-adjustment-cva" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="credit-value-adjustment-cva"><span class="header-section-number">9.2.2</span> Credit Value Adjustment (CVA)</h3>
<p><strong>CVA</strong> measures the expected loss from a counterparty’s potential default in OTC derivative transactions. It directly impacts a dealer’s financials:</p>
<ul>
<li>An <strong>increase in CVA</strong> reduces profits, as it represents higher expected credit losses.<br>
</li>
<li>CVA must be calculated for each counterparty to incorporate their specific default risk.</li>
</ul>
<p>CVA is a crucial risk management tool, as it reflects the financial cost of counterparty risk, helping dealers to price derivatives more accurately and align with regulatory and accounting requirements.</p>
<section id="calculations-for-cva" class="level4">
<h4 class="anchored" data-anchor-id="calculations-for-cva">Calculations for CVA</h4>
<p>To calculate <strong>Credit Value Adjustment (CVA)</strong>, the process involves discretizing the timeline of the longest derivative and estimating the potential losses over each interval.</p>
<ul>
<li><span class="math inline">\(T\)</span>: The life of the longest derivative.<br>
</li>
<li><span class="math inline">\([t_{i-1}, t_i]\)</span>: Intervals dividing <span class="math inline">\([0, T]\)</span>.<br>
</li>
<li><span class="math inline">\(q_i\)</span>: Risk-neutral probability of default during the <span class="math inline">\(i\)</span>th interval.<br>
</li>
<li><span class="math inline">\(v_i\)</span>: Present value of net exposure at the midpoint of the <span class="math inline">\(i\)</span>th interval.<br>
</li>
<li><span class="math inline">\(R\)</span>: Estimated recovery rate.<br>
</li>
<li><span class="math inline">\(s_i\)</span>: Credit spread for a maturity of <span class="math inline">\(t_i\)</span>.</li>
</ul>
<p>The total expected loss from counterparty default is calculated as: <span class="math display">\[
\text{CVA} = \sum_{i=1}^{n} (1 - R) q_i v_i
\]</span></p>
<p>The risk-neutral default probability (<span class="math inline">\(q_i\)</span>) for the <span class="math inline">\(i\)</span>th interval is given by: <span class="math display">\[
q_i = \exp \left( \frac{- s_{i-1} t_{i-1}}{1 - R} \right) - \exp \left( \frac{- s_i t_i}{1 - R} \right)
\]</span></p>
<p>The exposure (<span class="math inline">\(v_i\)</span>) is typically estimated using <strong>Monte Carlo simulations</strong>, which account for the uncertain nature of market values over time.</p>
</section>
<section id="collateral-and-cure-periods" class="level4">
<h4 class="anchored" data-anchor-id="collateral-and-cure-periods">Collateral and Cure Periods</h4>
<p>Collateral agreements influence the calculation of exposures. The <strong>exposure, <span class="math inline">\(E\)</span></strong>, is defined as: <span class="math display">\[
E = \max(V - C, 0)
\]</span></p>
<ul>
<li><span class="math inline">\(V\)</span>: Market value of outstanding transactions.</li>
<li><span class="math inline">\(C\)</span>: Collateral posted at the time of default.</li>
</ul>
<p>The <strong>cure period</strong>—typically 10 days—is the time between when a counterparty stops posting collateral and the close-out of the transaction. This affects the collateral’s value and must be modeled in the Monte Carlo simulation.</p>
</section>
<section id="peak-exposure" class="level4">
<h4 class="anchored" data-anchor-id="peak-exposure">Peak Exposure</h4>
<ul>
<li>Calculated at the midpoint of each interval and represents a high percentile (e.g., 97.5%) of potential exposures.<br>
</li>
<li><strong>Real-world simulations</strong> should ideally be used for this calculation, but for short time periods, risk-neutral simulations yield similar results.</li>
</ul>
</section>
<section id="downgrade-triggers" class="level4">
<h4 class="anchored" data-anchor-id="downgrade-triggers">Downgrade Triggers</h4>
<ul>
<li><strong>Downgrade triggers</strong> in ISDA agreements require increased collateral or termination of transactions when a party’s credit rating falls below a threshold.<br>
</li>
<li>Overuse of these triggers can lead to liquidity crises, as seen in cases such as AIG, Enron, Xerox, and Ambac.<br>
</li>
<li>While they provide some protection, they are limited in addressing sudden and severe credit rating declines.</li>
</ul>
</section>
</section>
<section id="the-impact-of-a-new-transaction" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="the-impact-of-a-new-transaction"><span class="header-section-number">9.2.3</span> The Impact of a New Transaction</h3>
<p>The addition of a new transaction to an existing portfolio can impact the Credit Value Adjustment (CVA) depending on its correlation with the existing transactions:</p>
<ul>
<li><strong>Positive correlation</strong> with existing transactions increases CVA, as it raises the potential exposure to the counterparty.</li>
<li><strong>Negative correlation</strong> reduces CVA, as the exposure to the counterparty becomes less correlated with existing positions, mitigating overall risk.</li>
</ul>
<p>Companies may receive more favorable quotes from dealers with whom they already have existing transactions, due to <strong>netting effects</strong> and CVA considerations. However, recalculating CVA for each new transaction can be computationally intensive. Instead, <strong>stored values</strong> from previous Monte Carlo simulations can be leveraged to efficiently update CVA incrementally without starting from scratch.</p>
</section>
<section id="cva-risk-and-wrong-way-risk" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="cva-risk-and-wrong-way-risk"><span class="header-section-number">9.2.4</span> CVA Risk and Wrong-Way Risk</h3>
<p>CVA can be thought of as a complex derivative position, and its management requires the same hedging techniques used for other derivatives. Since a rise in CVA results in a loss for the dealer, <strong>hedging CVA</strong> becomes essential.</p>
<p><strong>Computing Greek letters</strong> (such as delta, gamma, etc.) for CVA is computationally intensive, yet necessary for risk management. Regulators require that changes in credit spreads be incorporated into <strong>market risk capital</strong> calculations to reflect CVA risk.</p>
<ul>
<li><strong>Wrong-way risk</strong> occurs when the probability of default is <strong>positively correlated</strong> with exposure, increasing risk for the dealer.</li>
<li><strong>Right-way risk</strong> occurs when the default probability is <strong>negatively correlated</strong> with exposure, reducing risk for the dealer.</li>
</ul>
<p>Evaluating these types of risk requires an understanding of the counterparty’s business and the full scope of their other transactions. To adjust for wrong-way risk, regulators require a <strong>CVA adjustment</strong> using an <strong>alpha multiplier</strong> of at least <strong>1.2</strong>.</p>
</section>
<section id="debit-value-adjustment-dva" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="debit-value-adjustment-dva"><span class="header-section-number">9.2.5</span> Debit Value Adjustment (DVA)</h3>
<p><strong>Debit Value Adjustment (DVA)</strong> reflects the counterparty’s potential cost due to the dealer’s default. It is essentially the counterpart to CVA, representing the cost to the counterparty if the dealer defaults.</p>
<ul>
<li>DVA benefits the dealer, effectively offsetting the dealer’s CVA, which aligns with the zero-sum nature of derivatives markets.</li>
<li>The <strong>book value of derivatives</strong> is calculated as: <span class="math display">\[
f_{nd} - \text{CVA} + \text{DVA}
\]</span></li>
</ul>
<p>where <span class="math inline">\(f_{nd}\)</span> is the value of the derivative assuming no defaults.</p>
<p>An increase in the dealer’s <strong>credit spread</strong> results in an increase in DVA, which can boost reported profits. However, because this effect could artificially inflate profits, <strong>regulators exclude DVA gains and losses</strong> from the definition of <strong>common equity</strong> in regulatory capital calculations. This exclusion aims to prevent misrepresentation of financial stability.</p>
</section>
</section>
<section id="credit-value-at-risk-credit-var" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="credit-value-at-risk-credit-var"><span class="header-section-number">9.3</span> Credit Value at Risk (Credit VaR)</h2>
<p><strong>Credit VaR</strong> is a critical tool for regulatory capital determination and internal credit risk management. It measures the potential credit loss over a specified time horizon that will not be exceeded at a given confidence level.</p>
<ul>
<li>Can consider only default losses or include losses from downgrades and credit spread changes.</li>
<li>Banks use Credit VaR for regulatory capital (to comply with Basel requirements) and economic capital.</li>
<li>Credit VaR typically uses a longer horizon (e.g., one year) than market risk VaR (e.g., one day).</li>
<li>Credit risk models are more elaborate than those for market risk due to the need to capture interdependent defaults and potential downgrades.</li>
</ul>
<p>A critical variable in credit risk modeling is <strong>credit correlation</strong>, which accounts for the interdependence of defaults among companies in a portfolio. During economic downturns, increased credit correlation magnifies the risk for institutions, emphasizing its importance in stress testing and capital adequacy assessments.</p>
<section id="ratings-transition-matrices" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="ratings-transition-matrices"><span class="header-section-number">9.3.1</span> Ratings Transition Matrices</h3>
<p><strong>Ratings transition matrices</strong> quantify the likelihood of a company transitioning between credit ratings over a given time period, based on historical data.</p>
<p><strong>One-Year Ratings Transition Matrix, 1981–2020</strong> (Source: S&amp;P)</p>
<ul>
<li>Probabilities Expressed as Percentages and Adjustments for Transition to the NR (not rated) Category</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Initial Rating</th>
<th style="text-align: center;">AAA</th>
<th style="text-align: center;">AA</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">BBB</th>
<th style="text-align: center;">BB</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">CCC/C</th>
<th style="text-align: center;">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AAA</td>
<td style="text-align: center;">89.85</td>
<td style="text-align: center;">9.35</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">AA</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">90.76</td>
<td style="text-align: center;">8.08</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">1.67</td>
<td style="text-align: center;">92.61</td>
<td style="text-align: center;">5.23</td>
<td style="text-align: center;">0.27</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">3.45</td>
<td style="text-align: center;">91.93</td>
<td style="text-align: center;">3.78</td>
<td style="text-align: center;">0.46</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">BB</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">5.03</td>
<td style="text-align: center;">86.00</td>
<td style="text-align: center;">7.51</td>
<td style="text-align: center;">0.61</td>
<td style="text-align: center;">0.70</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">5.18</td>
<td style="text-align: center;">85.09</td>
<td style="text-align: center;">5.66</td>
<td style="text-align: center;">3.81</td>
</tr>
<tr class="odd">
<td style="text-align: center;">CCC/C</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">14.72</td>
<td style="text-align: center;">50.90</td>
<td style="text-align: center;">33.42</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">100.00</td>
</tr>
</tbody>
</table>
<ul>
<li>According to S&amp;P’s one-year transition matrix, a company rated ‘A’ has a 92.61% probability of maintaining its rating over one year.</li>
<li>Estimate multi-period transitions via matrix multiplication (e.g., a 5-year transition is derived by raising the 1-year matrix to the 5th power).</li>
<li><strong>Assumptions</strong>: Transition probabilities are independent across periods, which oversimplifies real-world scenarios, as downgrades often increase the probability of further downgrades.</li>
<li>Transition matrices are integral to <strong>CreditMetrics</strong>, enabling portfolio revaluation based on credit rating migrations.</li>
</ul>
</section>
<section id="methods-for-calculating-credit-var" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="methods-for-calculating-credit-var"><span class="header-section-number">9.3.2</span> Methods for Calculating Credit VaR</h3>
<ol type="1">
<li><strong>Vasicek’s Model</strong>:
<ul>
<li>Based on a one-factor Gaussian copula model.</li>
<li>Focuses on the time to default for portfolio companies.</li>
<li>Widely used for regulatory capital calculations.</li>
</ul></li>
<li><strong>Credit Risk Plus</strong>:
<ul>
<li>Introduced by Credit Suisse in 1997.</li>
<li>Inspired by insurance models, focusing on default probabilities and loss rates.</li>
<li>Incorporates uncertainty in default probabilities to calculate loss distributions.</li>
</ul></li>
<li><strong>CreditMetrics</strong>:
<ul>
<li>Developed by JPMorgan in 1997.</li>
<li>Combines Gaussian copula models with ratings transition matrices.</li>
<li>Measures both default and downgrade risks, producing a more comprehensive loss estimate.</li>
</ul></li>
</ol>
<ul>
<li>CreditMetrics and Credit Risk Plus, both aim to estimate long-term loss distributions.</li>
<li>Differences lie in <strong>timing</strong> of loss recognition:
<ul>
<li><strong>Credit Risk Plus</strong> recognizes losses only upon default.</li>
<li><strong>CreditMetrics</strong> considers revaluation losses for downgrades over time.</li>
</ul></li>
<li><strong>Example</strong>: If a loan is downgraded in Years 1 and 2 before defaulting in Year 3:
<ul>
<li>Credit Risk Plus calculates the loss only in Year 3.</li>
<li>CreditMetrics includes incremental revaluation losses in Years 1 and 2.</li>
</ul></li>
</ul>
</section>
<section id="credit-spread-risk" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="credit-spread-risk"><span class="header-section-number">9.3.3</span> Credit Spread Risk</h3>
<p><strong>Credit spread risk</strong> reflects changes in credit spreads, which can significantly impact the value of credit-sensitive products such as bonds and derivatives.</p>
<ol type="1">
<li><strong>Historical Simulation</strong>:
<ul>
<li>Uses historical data (e.g., the last 500 days of credit spread changes).</li>
<li>Limitation: Assumes no default probability and may lack sufficient data quality.</li>
</ul></li>
<li><strong>CreditMetrics</strong>:
<ul>
<li>Combines rating transition matrices and Monte Carlo simulations.</li>
<li>Accounts for the distribution of credit spreads over the simulation horizon.</li>
</ul></li>
</ol>
</section>
</section>
<section id="practice-questions-and-problems" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="practice-questions-and-problems"><span class="header-section-number">9.4</span> Practice Questions and Problems</h2>
<section id="estimating-default-probabilities-1" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="estimating-default-probabilities-1"><span class="header-section-number">9.4.1</span> Estimating Default Probabilities</h3>
<ol type="1">
<li>What is a rating?</li>
<li>What rating agencies exist and how many categories do they use for investment-grade bonds?</li>
<li>What are the disadvantages of ratings with respect to credit risk for financial institutions?</li>
<li>What are alternative methods for estimating credit risk?</li>
<li>What is meant by a hazard rate?</li>
<li>Calculate the average hazard rate for a B-rated company during the first year from the data in Table in the text.</li>
<li>Calculate the average hazard rate for a BB-rated company during the third year from the data in Table in the text.</li>
<li>A credit default swap requires a semiannual payment at the rate of 60 basis points per year. The principal is $300 million and the credit default swap is settled in cash. A default occurs after four years and two months, and the calculation agent estimates that the price of the cheapest deliverable bond is 40% of its face value shortly after the default. List the cash flows and their timing for the seller of the credit default swap.</li>
<li>Explain the two ways a credit default swap can be settled.</li>
<li>Explain the difference between the default probabilities calculated from historical default experience and those calculated from credit spreads.</li>
<li>The spread between the yield on a three-year corporate bond and the yield on a similar risk-free bond is 50 basis points. The recovery rate is 30%. Estimate the implied average hazard rate per year over the three-year period.</li>
<li>The spread between the yield on a five-year bond issued by a company and the yield on a similar risk-free bond is 80 basis points. Assuming a recovery rate of 40%, estimate the implied average hazard rate per year over the five-year period. If the spread is 70 basis points for a three-year bond, what do your results indicate about the implied average hazard rate in years 4 and 5?</li>
<li>How are recovery rates usually defined?</li>
<li>“The position of a buyer of a credit default swap is similar to the position of someone who is long a risk-free bond and short a corporate bond.” Explain this statement.</li>
<li>Why is there a potential asymmetric information problem in credit default swaps?</li>
</ol>
</section>
<section id="xvas-1" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="xvas-1"><span class="header-section-number">9.4.2</span> xVAs</h3>
<ol type="1">
<li>Explain why a new transaction by a bank with a counterparty can have the effect of increasing or reducing the bank’s credit exposure to the counterparty.</li>
<li>A company offers to post its own equity as collateral. How would you respond?</li>
<li>Can the existence of default triggers increase default risk? Explain your answer.</li>
<li>Give two examples of when (a) wrong-way risk and (b) right-way risk can be expected to be observed.</li>
<li>Explain the term “cure period.”</li>
<li>“Netting means that CVA cannot be calculated on a transaction-by-transaction basis.” Explain this statement.</li>
<li>“DVA can improve the bottom line when a bank is experiencing financial difficulties.” Explain why this is so.</li>
<li>What part of CVA risk is considered a component of market risk by regulators?</li>
</ol>
</section>
<section id="credit-value-at-risk" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="credit-value-at-risk"><span class="header-section-number">9.4.3</span> Credit Value at Risk</h3>
<ol type="1">
<li>Explain the difference between Vasicek’s model, the Credit Risk Plus model, and CreditMetrics as far as the following are concerned: (a) when a credit loss is recognized and (b) the way in which default correlation is modeled.</li>
<li>Explain what is meant by the constant level of risk assumption.</li>
<li>Use the transition matrix from the text to calculate a transition matrix for three years. What is the probability of a company rated AAA being AAA at the end of two years? What is the probability of it moving to AA?</li>
<li>How can historical simulation be used to calculate a one-day 99% VaR for the credit risk of bonds in the trading book? What are the disadvantages?</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./week_08.html" class="pagination-link" aria-label="Market Risk II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Market Risk II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./week_10.html" class="pagination-link" aria-label="Operational Risk, Liquidity Risk, and Model Risk">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Operational Risk, Liquidity Risk, and Model Risk</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>